"""Add assets table

Revision ID: 157b1d4f323d
Revises: 5da3eb8d710e
Create Date: 2025-09-17 18:49:01.389539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157b1d4f323d'
down_revision = '5da3eb8d710e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
