"""add_otp_verification_table

Revision ID: 7e80867f99f2
Revises: a3f81be4440f
Create Date: 2025-09-05 00:12:29.992313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e80867f99f2'
down_revision = 'a3f81be4440f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
