"""Add content column to assets

Revision ID: 939a9d92a634
Revises: ef49399cb8ce
Create Date: 2025-09-24 03:31:11.600100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939a9d92a634'
down_revision = 'ef49399cb8ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'content')
    # ### end Alembic commands ###
