"""add_boards_table

Revision ID: a4d591e16243
Revises: 7e80867f99f2
Create Date: 2025-09-05 01:19:04.657965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d591e16243'
down_revision = '7e80867f99f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
